### PR TITLE
Allow `message` to be inherited from prototype

### PR DESCRIPTION
**Pull request by kenvunz**

### CODE REVIEW

**Comment by kenvunz** [comment]
Not sure why there would be a merge conflicts as it's such a little change.
Let me know if I need to update / fix the Pull Request

**Comment by dasilvacontin** [comment]
Probably because I changed the indentation style. Try rebasing with master. Let me know if you need help with that.

**Comment by kenvunz** [comment]
Should be sweet now

**Comment by dasilvacontin** [comment]
Could you squash commits? Thanks!

**Comment by kenvunz** [comment]
squashed! :)

**Comment by dasilvacontin** [comment]
LGTM, thanks for the PR! :)

**Pull request merged**
