### PR TITLE
Fix node.js v0.12

### PR DESCRIPTION
**Pull request by tonila**
First pull request I made broke the inheritance chain, so here is another try.

I need to thank B T for pointing me to right direction:
http://stackoverflow.com/a/17936621/2164432

### CODE REVIEW

**Comment by dasilvacontin** [comment]
Hi! Thanks for the PR. I'll try checking this out asap.

**Comment by dasilvacontin** [comment]
Related to #2. I added some tests to master. Rebase and check if Travis' build succeeds. Thanks! :)

And squash commits when you are done!

**Comment by tonila** [comment]
Hi,

Travis build succeeds now. 

Merging separate repos and Travis are new things for me, so I hope I did it right.

**Comment by dasilvacontin** [comment]
Awesome! The only thing left is squashing commits. Here's a guide, if it's your first time: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

You will also need to force push to your branch, as mentioned in this stackoverflow question: http://stackoverflow.com/questions/5667884/how-to-squash-commits-in-git-after-they-have-been-pushed

Thanks!

**Comment by dasilvacontin** [comment]
If you need to rebase to the repo's master branch, you should add the main (upstream) repo as a remote, and rebase to its latest changes:

``` bash
git remote add upstream https://github.com/dasilvacontin/subclass-error
git fetch upstream
git rebase upstream/master
```

**Comment by tonila** [comment]
Ok, I Did some squashing.

**Comment by dasilvacontin** [comment]
There should be only 1 commit, actually. The commit of merging my master to your branch is not necessary.

**Comment by tonila** [comment]
Ok, one more try.

**Comment by tonila** [comment]
Huh! Now there is only one commit. I did not even realize I can do this kind of stuff with git. Thanks for an important lesson!

**Comment by tonila** [comment]
And I only now saw your tip how to rebase to main repo latest changes. I was doing it wrong...

**Comment by dasilvacontin** [comment]
No worries, glad to help! And thanks for the awesome PR!

I also learned to squash/rebase because of 'fixing' a PR. :)

**Pull request merged**
